import { PackageCheck } from 'lucide-react';
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { api } from '../services/api';

export default function OrdersPage(){const{user}=useAuth();const[orders,setOrders]=useState([]);const[loading,setLoading]=useState(true);useEffect(()=>{if(user)api('/orders').then(d=>setOrders(d.orders)).finally(()=>setLoading(false));else setLoading(false)},[user]);
if(!user)return<section className="container-app py-24"><div className="card mx-auto max-w-lg p-10 text-center"><PackageCheck className="mx-auto text-green-600" size={52}/><h1 className="mt-5 text-3xl font-black">Login to view orders</h1><Link to="/login?redirect=/orders" className="btn-primary mt-7">Login</Link></div></section>;
return<section className="container-app py-14"><h1 className="text-4xl font-black">My orders</h1><p className="mt-2 text-stone-500">Track your recent grocery orders.</p><div className="mt-8 space-y-4">{loading?<p>Loading...</p>:orders.length?orders.map(o=><article key={o.id} className="card p-6"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-wider text-green-600">Order #{o.id?.slice(-6) || 'N/A'}</p><h2 className="mt-1 font-black">₹{o.total}</h2></div><span className="rounded-full bg-green-100 px-4 py-2 text-sm font-bold text-green-700">{o.status}</span></div><div className="mt-5 border-t pt-4 text-sm text-stone-500">{o.items.map(i=>`${i.name} × ${i.quantity}`).join(' · ')}</div><p className="mt-2 text-xs text-stone-400">{new Date(o.createdAt).toLocaleString()}</p></article>):<div className="card p-10 text-center"><p className="font-bold">No orders yet.</p><Link to="/products" className="mt-3 inline-block text-green-700">Shop now →</Link></div>}</div></section>}
